image: node:6

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm run lint
    - npm test
  cache:
    paths:
      - node_modules/
  coverage: /^Statements\s*:\s*([^%]+)/

build:
  stage: build
  only:
    - tags
  before_script:
    - apt-get update
    - apt-get install -y jq
  script:
    - npm install
    - npm pack
    - mkdir bin
    - cp "metafig-$(cat package.json | jq -r .version).tgz" bin/
  artifacts:
    paths:
      - bin/

deploy:
  stage: deploy
  only:
    - tags
  image: ruby:2.4
  before_script:
    - apt-get update
    - apt-get install -y jq
  script:
    - gem install fury
    - fury push ./bin/metafig-$(cat package.json | jq -r .version).tgz --api-token $GEMFURY_TOKEN
