language: node_js
node_js:
  - "8"
  - "7"
  - "6"

script:
  - npm run preflight

jobs:
  include:
    - stage: npm release
      node_js: "7"
      script:
        - echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on:
          tags: true
